//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminCV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int ID_Education { get; set; }
        public int Institution_ID { get; set; }
        public int Degree_ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Institution Institution { get; set; }
    }
}
