//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminCV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language_level
    {
        public int ID_Language_Level { get; set; }
        public int Language_ID { get; set; }
        public int Level_ID { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Level Level { get; set; }
    }
}
