//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminCV.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int ID_WorkExperience { get; set; }
        public int Company_ID { get; set; }
        public int Position_ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Position Position { get; set; }
    }
}
