//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectCV2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalSkills
    {
        public int ID_PersonalSkill { get; set; }
        public string Managerial_skills { get; set; }
        public string Digital_competences { get; set; }
        public string Communication_skills { get; set; }
        public string Job_related_skills { get; set; }
    }
}
